# -*- coding: utf-8 -*-
#
# AIMS Python documentation build configuration file, created by
# sphinx-quickstart on Mon Mar 19 22:39:45 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
# 
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys

# CLOUD: import Cloud
import cloud_sptheme as csp

def setup(app):
    app.add_css_file('style.css')

sys.path.insert(0, os.path.abspath('.'))

# Things to be installed, with miniconda or package manager:
#  cloud_sptheme
#  pbr
#  sphinxcontrib-fulltoc
#  sphinxcontrib.programoutput
# NB: we prefer to use imgmath than mathjax, for offline reading and 
# some backend security stuff.  As part of this, build machine should have
# at least one of these packages (see http://www.sphinx-doc.org/en/1.6/ext/math.html#module-sphinx.ext.imgmath):
#  dvipng dvisvgm
# NB: we now leant toward SVG, because they seem sharper

# USEFUL RST/SPHINX doc pages:
# for items on this page:
#   https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-gettext_compact
# general:
#   https://docutils.sourceforge.io/docs/user/rst/quickref.html
# for directives: 
#   https://docutils.sourceforge.io/docs/ref/rst/directives.html


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'


# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.imgmath', 
    'sphinxcontrib.fulltoc',
    'sphinx.ext.todo',
    'cloud_sptheme.ext.table_styling',
    'sphinxcontrib.programoutput',
    'hidden_code_block' # from A. Scopatz
]

html_math_renderer     = 'imgmath'
imgmath_image_format   = 'svg'
imgmath_font_size      = 14
# use "--exact" so that the math text boxes don't get clipped
imgmath_dvisvgm_args   = ['--no-fonts', '--exact'] 
# use textcomp and mathptmx to get heavier (= easier to read) fonts in
# the math eqs
imgmath_latex_opts     = ["\\usepackage{textcomp}", 
                          "\\usepackage{mathptmx}"]
imgmath_latex_preamble = "".join(imgmath_latex_opts)

#    'sphinx.ext.ifconfig', 

todo_include_todos = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']
 
# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'NIfTI docs'
copyright = u'2004, NIfTI Data Format Working Group (DFWG)'
author = u'NIfTI DFWG'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'1.0'
# The full version, including alpha/beta/rc tags.
release = u'1.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
###language = None
###language = 'English'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
# CLOUD: set the html theme; there is also a red-colored version named
# "redcloud"
html_theme = 'cloud'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
html_theme_path = [csp.get_theme_dir()]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# html_compact_lists = True  ###  annoyingly, broken/ignored!
html_show_sphinx      = True      # eh, fine.
html_secnumber_suffix = ".  "     # would empty space be more readable?
smartquotes           = False     # quotes are simple: better cut+paste?
# .... and more options here:
# https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-smartquotes


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# CLOUD: [optional] set some of the options listed above...
# ... we can/will edit these a lot; specify colors, etc.
### Note for the main text font ('bodyfont'): rather than using
### 'bodyfont' in this dictionary, the main text font should be
### controlled in _static/style.css and the *.ttf files there,
### specifying the body->font-family there
#### **BUT** note that we now include bodyfont/fontscssurl here, too,
#### with the same font, so that googleapis is not pinged, because
#### that will slow down page viewing even from just local copy
# More items to be listed below can be found, in the theme.conf for
# the utilized cloud_sptheme, which can be found somewhere like here:
# ~/.conda/pkgs/cloud_sptheme-1.10.0-py_0/site-packages/cloud_sptheme/themes/cloud/theme.conf
html_theme_options = { 
    "stickysidebar": "true",
    "collapsiblesidebar": "true",
    "defaultcollapsed": "false",
    "roottarget": "index",
    "min_height": "12in",
    "max_width": "12in", 
    "lighter_header_decor": "true",
    "linkcolor": "#1874CD",
    "bgcolor": "#F5F5F5",
    #"bodylineheight": "1.4em",
    "footertextcolor" : "#F2D41E", # paler yellow than "#F2D41E",
    "rubricbgcolor": "#8B0000",
    "linkcolor": "#800000", # "#1874CD",
    #"toc_current_text_color" :  "#F2D41E", # too bright yellow on gray
    "headtextcolor": "#000000", #"#800000",
    "bodyfont": "local_PT_sans",  
    "fontcssurl" : "local_PT_sans",
    #"headfont": "PT Sans, sans-serif",
    #"bodyfont": "Ubuntu, PT Sans, sans-serif",
    #"bodyfont": "https://fonts.googleapis.com/css2?family=PT+Sans",
    #"fontcssurl" : "//fonts.googleapis.com/css?family=PT+Sans|Noticia+Text|Open+Sans|Droid+Sans+Mono|Roboto",
    #"fontcssurl" : "//fonts.googleapis.com/css?family=Ubuntu|Noto+Sans+JP|PT+Sans|Noticia+Text|Open+Sans|Droid+Sans+Mono|Roboto",
    "headlinkcolor": "#000000",  
    "headtrimcolor": "#000000",
    "sectiontextcolor" : "#800000", # think this is ignored bc they are links
    "sectionbgcolor" : "#008000", #"#f5dd4e", #"#F2D41E",
    "section_radius" : "0px",
    "sectiontrimcolor" :  "rgba(0,0,0,.125)",
    "codevarfont":  "Menlo,  monospace",
    "codeblockfont": "Menlo, monospace",
    "codetrimcolor":  "#E0EEE0" , #"#E0EEE0", #"#00C957",
    "codebgcolor":    "#E0EEE0" , # "#E0EEE0",
    "quotebgcolor"     : "rgba(0,0,0,.075)",
    "quotetrimcolor"   : "rgba(0,0,0,0.1)", # def was 0.05; make either 0 or 0.1
    "relbarbgcolor" : "#ad0000", # navbar bkgd, lighter red than: #"#800000",
    "highlightcolor": "#FFEC8B",
    #"sidebarhighcolor": "#800000",
    #"sidebarbgcolor" :  "#800000",
    #"sidebartextcolor": "#B0B0B0",
    #"sidebarlinkcolor": "#F5F5F5",
    #"sidebarhighcolor" :"#F2D41E",
    #"sidebartrimcolor" : "#008000",
    #"sidebardetailcolor" :"#F2D41E",
    #"sidebar_button_bg" : "#F2D41E",
    #"footerbgcolor": "#800000", #"#008000",
    "linkcolor": "#008000", #"#1874CD",
}

#    "headfont" : "Open Sans, sans-serif",


# see also: 
# ~/.local/lib/pyathon2.7/site-packages/cloud_sptheme/themes/cloud/theme.conf
# http://www.sphinx-doc.org/en/stable/theming.html
# some colors:
# aims red:  "#800000"
# green: "#008000"
# yellow-gold: "#F2D41E"
# white: "#ffffff"
# black: "#000000"
# med gray: "#B0B0B0"
# light gray: "#d5d5d4"
# med/light gray: "#d0d0d0"

''' 
From AFNI documentation, just as further examples:
html_theme_options = { 
    "stickysidebar": "true",
    "collapsiblesidebar": "true",
    "defaultcollapsed": "false",
    "roottarget": "index",
    "min_height": "12in",
    "max_width": "16in",
    "lighter_header_decor": "true",
    "linkcolor": "#1874CD",
    "bgcolor": "#F5F5F5",
    "bodyfont": "Arial",
    "bodylineheight": "1.4em",
    "codevarfont":  "Menlo,  monospace",
    "codeblockfont": "Menlo, monospace",
    "codetrimcolor": "#00C957",
    "codebgcolor": "#E0EEE0",
    "highlightcolor": "#FFEC8B",
    "headtextcolor": "#8B0000",
    "headlinkcolor": "#8B0000",
    "rubricbgcolor": "#8B0000",
    "headtextcolor": "#8B0000",
    "headlinkcolor": "#8B0000"
} 
'''

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': ['globaltoc.html', 'sourcelink.html', 'searchbox.html'],
    'using/windows': ['windowssidebar.html', 'searchbox.html']
}
 
### old:
#html_sidebars = {
#    '**': [
#        'relations.html',  # needs 'show_related': True theme option to display
#        'searchbox.html',
#    ]
#}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'NIfTIdocs'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'NIfTIdocs.tex', u'NIfTI Documentation',
     u'NIfTI DFWG', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'niftidocs', u'NIfTI DFWG',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'NIfTIdocs', u'NIfTI documentation',
     author, 'NIfTI DFWG', 'One line description of project.',
     'Miscellaneous'),
]



